server:
  port: 8083
  shutdown: graceful
spring:
  main:
    register-shutdown-hook: true #默认true,设置false优雅停机也会失效
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  application:
    name: king-dog

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

#  cloud:
#    nacos:
#      discovery:
#        # 服务注册地址
#        server-addr: 127.0.0.1:8848
udp:
  port: 18080

netty:
  port: 8888