server:
  port: 8080
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  application:
    name: movie-service


eureka:
  client:
    service-url:
      defaultZone: http://192.168.2.161:8761/eureka/
  instance:
    prefer-ip-address: true

udp:
  port: 18080